### ISSUE TITLE
Discrepancy of parameters in paper vs examples

### ISSUE THREAD

**Issue by Zinoex** [Kiguli/IMPaCT#1]
Hi Ben,

Before I ask my questions, I just want to thank you for making a general tool with such a nice interface and very few implicit assumptions!

I have noticed a couple of discrepancies between the parameters listed in [the paper](https://arxiv.org/pdf/2401.03555) and what's present in the examples. Can I please ask you to clarify if this is deliberate to fit the examples into the tool or if this is a mistake? 

2D Robot (all specs): the reach and avoid regions have different bounds between the paper and the examples [1](https://github.com/Kiguli/IMPaCT/blob/main/examples/ex_2Drobot-RA-U/robot2D.cpp) [2](https://github.com/Kiguli/IMPaCT/blob/main/examples/ex_2Drobot-RA-D/robot2D.cpp) [3](https://github.com/Kiguli/IMPaCT/blob/main/examples/ex_2Drobot-R-U/robot2D.cpp) [4](https://github.com/Kiguli/IMPaCT/blob/main/examples/ex_2Drobot-R-D/robot2D.cpp).
2D Robot (all specs): the factor for the (affine) control is 10 in the paper and 2 in the examples [1](https://github.com/Kiguli/IMPaCT/blob/main/examples/ex_2Drobot-RA-U/robot2D.cpp) [2](https://github.com/Kiguli/IMPaCT/blob/main/examples/ex_2Drobot-RA-D/robot2D.cpp) [3](https://github.com/Kiguli/IMPaCT/blob/main/examples/ex_2Drobot-R-U/robot2D.cpp) [4](https://github.com/Kiguli/IMPaCT/blob/main/examples/ex_2Drobot-R-D/robot2D.cpp).
4D BAS: the standard deviation between the paper and [the example](https://github.com/Kiguli/IMPaCT/blob/main/examples/ex_4DBAS-S/BAS4D.cpp) do no match.
4D BAS: The eta in the paper appears to apply to a 2D input space, while the input space is in fact 1D.
7D BAS: the standard deviation between the paper and [the example](https://github.com/Kiguli/IMPaCT/blob/main/examples/ex_7DBAS-S/BAS7D.cpp) do no match.

I suspect for both BAS examples that the paper is missing a reciprocal for each variance.

While at it, can I also you to clarify why for the 2D robot (R-A) example bounds along each axis of -10..10 with eta = 0.5 results in 41, rather than 40 states?

**Comment by Kiguli** [comment]
Hi Frederik,

Thanks for your detailed question. In the cases you mention these are just an honest mistake when typing up the paper, I had tried (and it appears failed!) to be very thorough with correctly presenting all of the parameters we used for the case studies. 

_**I would like to highlight that these typos shouldn't have any meaningful effect on the performance times documented in the paper.**_

As you suggested the BAS examples are simply missing the reciprocal, and the input space being 2D is just a typo. For the robot cases again these are typos probably caused by several variants of the same case studies floating around in different papers. The areas we consider are quite close to the ones written even if they are incorrect, so there is not a big difference in that respect. The dynamics affine term is a typo, and certainly not meant to mislead.

Regarding the reason there are 41 states rather than 40, we consider both the bounds of the closed set as grid cell centres and discretise from there. You can see this visually in the robot figures. The tool SCOTS does the same thing, and I believe the purpose is for when the gridding doesn't divide well into the range of the closed set. For case studies you may need to factor this in if it is important to the system at hand having the hard border. I believe at one point I planned to include an option for both this way and also the one that would give 40, probably due to time restrictions the feature was cut, but it could be included in future if it would be valuable.

I know you concurrently created a similar tool and I would happy to chat more and compare implementation notes via email if you are interested :)
